### ISSUE TITLE
CosmicTools 1.x.x-3.x.x, Selenium Downloads to User Downloads Folder

### ISSUE THREAD

**Issue by DarkenLM** [Y2Kwastaken/CosmicTools#4]
Comic Tools is downloading the latest Cosmic Reach release to the default Downloads directory on windows, instead of the current one, causing the process to halt.

# Steps to Reproduce
1. Download Release 2.1.0-SNAPSHOT
2. Run the command `java -jar CosmicTools.jar --decompile --driver=FIREFOX`, or `java -jar CosmicTools.jar --driver=FIREFOX--cwd=temp --ignore-cache --decompile`
3. Go to Windows' default download location (`%UserProfile%\Downloads`) and see a new file `cosmic-reach-jar(<number>).zip` there.

**Comment by Y2Kwastaken** [comment]
## Why Won't It Be Fixed
As far as I'm aware as of now Selenium has no consistent way for every driver type to dictate a downloads folder.

## How To Fix The Issue
If you encounter this issue. Enter your downloads folder and uninstall all instances of `cosmic-tools-jar.zip` even those with numbering etc.

## How can I avoid encountering this Issue

### 1.x.x and 2.x.x

Do not download cosmic-reach-jar.zip from other sources outside of CosmicTools and if you do delete the zip once it has been used up so CosmicTools can function as intended

### 3.x.x

If you want to avoid this situation in CosmicTools 3.x.x you can set the download source to the unofficial archive using the argument `--source=unofficial_archive_github`. However remember that this archive is unofficial and may be prone to issues.
